/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lineItem 
 * @param giftCertificate 
 */
@JsonClass(generateAdapter = true)
data class CartUpdateRequest (

    @Json(name = "line_item")
    val lineItem: LineItemRequestData? = null,

    @Json(name = "gift_certificate")
    val giftCertificate: LineItemGiftCertificateRequestData? = null

)

