/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lineItems 
 * @param giftCertificates 
 * @param customItems 
 */
@JsonClass(generateAdapter = true)
data class CartLineItemUpdatePost (

    @Json(name = "line_items")
    val lineItems: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "gift_certificates")
    val giftCertificates: kotlin.collections.List<LineItemGiftCertificateRequestData>? = null,

    @Json(name = "custom_items")
    val customItems: kotlin.collections.List<kotlin.Any>? = null

)

