/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param customerId 
 * @param lineItems 
 * @param customItems 
 * @param giftCertificates 
 * @param channelId If no channel is specified, defaults to 1. 
 * @param currency 
 * @param locale Accepts string of format `xx` or `xx-YY`.
 */
@JsonClass(generateAdapter = true)
data class CartCreatePostData (

    @Json(name = "customer_id")
    val customerId: kotlin.Int? = null,

    @Json(name = "line_items")
    val lineItems: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "custom_items")
    val customItems: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "gift_certificates")
    val giftCertificates: kotlin.collections.List<LineItemGiftCertificateRequestData>? = null,

    /* If no channel is specified, defaults to 1.  */
    @Json(name = "channel_id")
    val channelId: kotlin.Int? = null,

    @Json(name = "currency")
    val currency: CartCreatePostDataCurrency? = null,

    /* Accepts string of format `xx` or `xx-YY`. */
    @Json(name = "locale")
    val locale: kotlin.String? = null

)

