/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * This will always be the same between cart and checkout.
 *
 * @param code ISO-4217 currency code. (See: http://en.wikipedia.org/wiki/ISO_4217.)
 */
@JsonClass(generateAdapter = true)
data class Currency (

    /* ISO-4217 currency code. (See: http://en.wikipedia.org/wiki/ISO_4217.) */
    @Json(name = "code")
    val code: kotlin.String? = null

)

