/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cartUrl 
 * @param checkoutUrl 
 */
@JsonClass(generateAdapter = true)
data class InlineResponse201 (

    @Json(name = "cart_url")
    val cartUrl: kotlin.String? = null,

    @Json(name = "checkout_url")
    val checkoutUrl: kotlin.String? = null

)

