/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param downloadFileUrls URLs to download all product files.
 * @param downloadPageUrl The URL for the combined downloads page.
 * @param downloadSize Combined download size, in human-readable style. E.g.: `30MB`.
 */
@JsonClass(generateAdapter = true)
data class ItemDigitalAllOf (

    /* URLs to download all product files. */
    @Json(name = "download_file_urls")
    val downloadFileUrls: kotlin.collections.List<kotlin.String>? = null,

    /* The URL for the combined downloads page. */
    @Json(name = "download_page_url")
    val downloadPageUrl: kotlin.String? = null,

    /* Combined download size, in human-readable style. E.g.: `30MB`. */
    @Json(name = "download_size")
    val downloadSize: kotlin.String? = null

)

