/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param theme Currently supports `Birthday`, `Boy`, `Celebration`, `Christmas`, `General`, and `Girl`.
 * @param amount Value must be between 1.00 and 1,000.00 in the store's default currency.
 * @param sender 
 * @param recipient 
 * @param id 
 * @param name GiftCertificate-provided name that will appear in the control panel.
 * @param isTaxable 
 * @param message Limited to 200 characters.
 */
@JsonClass(generateAdapter = true)
data class ItemGiftCertificate (

    /* Currently supports `Birthday`, `Boy`, `Celebration`, `Christmas`, `General`, and `Girl`. */
    @Json(name = "theme")
    val theme: kotlin.String,

    /* Value must be between 1.00 and 1,000.00 in the store's default currency. */
    @Json(name = "amount")
    val amount: java.math.BigDecimal,

    @Json(name = "sender")
    val sender: ContactEntity,

    @Json(name = "recipient")
    val recipient: ContactEntity,

    @Json(name = "id")
    val id: kotlin.String? = null,

    /* GiftCertificate-provided name that will appear in the control panel. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "is_taxable")
    val isTaxable: kotlin.Boolean? = null,

    /* Limited to 200 characters. */
    @Json(name = "message")
    val message: kotlin.String? = null

)

