/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param quantity 
 * @param productId 
 * @param variantId Required if the product has variants
 * @param listPrice 
 * @param optionSelections 
 */
@JsonClass(generateAdapter = true)
data class LineItemRequestData (

    @Json(name = "quantity")
    val quantity: java.math.BigDecimal,

    @Json(name = "product_id")
    val productId: java.math.BigDecimal,

    /* Required if the product has variants */
    @Json(name = "variant_id")
    val variantId: java.math.BigDecimal,

    @Json(name = "list_price")
    val listPrice: java.math.BigDecimal? = null,

    @Json(name = "option_selections")
    val optionSelections: kotlin.collections.List<ProductOptionSelection>? = null

)

