/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param physicalItems 
 * @param digitalItems 
 * @param giftCertificates 
 * @param virtualItems 
 */
@JsonClass(generateAdapter = true)
data class LineItem (

    @Json(name = "physical_items")
    val physicalItems: kotlin.collections.List<kotlin.Any>,

    @Json(name = "digital_items")
    val digitalItems: kotlin.collections.List<kotlin.Any>,

    @Json(name = "gift_certificates")
    val giftCertificates: kotlin.collections.List<ItemGiftCertificate>? = null,

    @Json(name = "virtual_items")
    val virtualItems: kotlin.collections.List<ItemCustom>? = null

)

