/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Given name for gift certificate line item.
 * @param theme Currently supports `Birthday`, `Boy`, `Celebration`, `Christmas`, `General`, and `Girl`.
 * @param amount 
 * @param quantity 
 * @param sender 
 * @param recipient 
 * @param message Message shown to recipient, as provided by sender.
 */
@JsonClass(generateAdapter = true)
data class LineItemGiftCertificateRequestData (

    /* Given name for gift certificate line item. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Currently supports `Birthday`, `Boy`, `Celebration`, `Christmas`, `General`, and `Girl`. */
    @Json(name = "theme")
    val theme: kotlin.String,

    @Json(name = "amount")
    val amount: java.math.BigDecimal,

    @Json(name = "quantity")
    val quantity: kotlin.Int,

    @Json(name = "sender")
    val sender: ContactEntity,

    @Json(name = "recipient")
    val recipient: ContactEntity,

    /* Message shown to recipient, as provided by sender. */
    @Json(name = "message")
    val message: kotlin.String? = null

)

