/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param optionId 
 * @param optionValue 
 */
@JsonClass(generateAdapter = true)
data class ProductOptionSelection (

    @Json(name = "option_id")
    val optionId: java.math.BigDecimal? = null,

    @Json(name = "option_value")
    val optionValue: kotlin.String? = null

)

