/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.commerce.common.api.bigcommerce.carts.v3.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name The product option name. For example, Color or Size
 * @param nameId The product option identifier.
 * @param `value` The product option value. For example, Red or Medium
 * @param valueId The product option value identifier.
 */
@JsonClass(generateAdapter = true)
data class ProductOption (

    /* The product option name. For example, Color or Size */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The product option identifier. */
    @Json(name = "name_id")
    val nameId: java.math.BigDecimal? = null,

    /* The product option value. For example, Red or Medium */
    @Json(name = "value")
    val `value`: kotlin.String? = null,

    /* The product option value identifier. */
    @Json(name = "value_id")
    val valueId: java.math.BigDecimal? = null

)

