name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      TERM: dumb

    steps:
      - uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Set up gradle.properties
        run: mkdir -p ~/.gradle; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build
        run: ./gradlew clean assemble test check

      - name: Upload build artifacts (Compose Commerce)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs-compose-commerce
          path: apps/compose-commerce/app/build/outputs

      - name: Upload build artifacts (Compose Search)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs-compose-search
          path: apps/compose-search/app/build/outputs

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            **/build/reports/*

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-results
          path: |
            **/build/test-results/*